/* eslint-disable */
export const blogs = [
  {
    id: 1,
    title: '9 Ways to Flight Booking of the Competition as a Retailer',
    author: 'Olivia Bennett',
    author_title: 'UI Designer',
    category: 'flight',
    rating: 8,
    created_date: new Date(),
    image: '/assets/background-images/blogTest.png',
    tags: ['tag1', 'tag2', 'tag3'],
    author_image: 'https://images.unsplash.com/photo-1658998765622-962cb51e7888?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3240&q=80',
    description: `Olivia Bennett is a talented UI Designer with a passion for creating user-friendly interfaces. With several years of experience in the field, Kristian has a keen eye for design and a deep understanding of user behavior. In this blog post, Kristian shares 9 valuable tips for retailers to outperform the competition in flight booking.`,
  },
  {
    id: 2,
    title: 'Top 20 Hotel Booking System By Domain Authority',
    author: 'Ethan Carter',
    author_title: 'UI Designer',
    category: 'car',
    rating: 5,
    created_date: new Date(),
    image: '/assets/background-images/blogTest.png',
    tags: ['tag1', 'tag2', 'tag3'],
    author_image: 'https://images.unsplash.com/photo-1658998765625-8fb3f5bfeb97?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3240&q=80',
    description: `Ethan Carter, a seasoned UI Designer, explores the top 20 hotel booking systems ranked by domain authority. With a keen eye for user experience, Christopher provides valuable insights into choosing the right platform for your hotel booking needs.`,
  },
  {
    id: 3,
    title: 'Top 20 Hotel Booking System By Domain Authority',
    author: 'Maya Rodriguez',
    author_title: 'Full-Stack Developer',
    category: 'hotel',
    rating: 5,
    created_date: new Date(),
    image: '/assets/background-images/blogTest.png',
    tags: ['tag1', 'tag2', 'tag3'],
    author_image: 'https://images.unsplash.com/photo-1658998765625-8fb3f5bfeb97?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3240&q=80',
    description: `Maya Rodriguez, a skilled Full-Stack Developer, delves into the world of hotel booking systems. With expertise in both front-end and back-end development, Santiago provides a comprehensive overview of the top 20 systems and their features.`,
  },
  {
    id: 4,
    title: 'Top 20 Hotel Booking System By Domain Authority',
    author: 'Liam Anderson',
    author_title: 'CEO',
    category: 'flight',
    rating: 8,
    created_date: new Date(),
    image: '/assets/background-images/blogTest.png',
    tags: ['tag1', 'tag2', 'tag3'],
    author_image: 'https://images.unsplash.com/photo-1658998765621-2cf0f12e059f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3240&q=80',
    description: `Liam Anderson, a visionary CEO, explores the realm of flight booking systems. With a wealth of experience in the travel industry, Adrian shares his insights into the top systems that can help retailers soar above the competition.`,
  },
  {
    id: 5,
    title: 'Top 20 Hotel Booking System By Domain Authority',
    author: 'Ava Williams',
    author_title: 'UI Designer',
    category: 'car',
    rating: 9,
    created_date: new Date(),
    image: '/assets/background-images/blogTest.png',
    tags: ['tag1', 'tag2', 'tag3'],
    author_image: 'https://images.unsplash.com/photo-1658998765621-2cf0f12e059f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3240&q=80',
    description: `Ava Williams, a talented UI Designer, takes you on a journey through the top 20 car booking systems ranked by domain authority. With a knack for creating visually appealing interfaces, Mentor shares her expertise on choosing the right platform for car reservations.`,
  },
];