// Details
export const flightDetails = [
  {
    from: 'DAC',
    fromCountry: 'Dhaka',
    fromTime: '08:45 AM',
    to: 'DXB',
    toCountry: 'Dubai',
    toTime: '01:05 PM',
    flightType: 'nonstop',
    duration: '5h 20m',
    date: 'Thu, 19 Aug',
    price: 350,
  },
  {
    from: 'DAC',
    fromCountry: 'Dhaka',
    fromTime: '08:45 AM',
    to: 'DXB',
    toCountry: 'Dubai',
    toTime: '01:05 PM',
    flightType: 'nonstop',
    duration: '5h 20m',
    date: 'Thu, 19 Aug',
    price: 350,
  },
  {
    from: 'DAC',
    fromCountry: 'Dhaka',
    fromTime: '08:45 AM',
    to: 'DXB',
    toCountry: 'Dubai',
    toTime: '01:05 PM',
    flightType: 'nonstop',
    duration: '5h 20m',
    date: 'Thu, 19 Aug',
    price: 350,
  },
  {
    from: 'DAC',
    fromCountry: 'Dhaka',
    fromTime: '08:45 AM',
    to: 'DXB',
    toCountry: 'Dubai',
    toTime: '01:05 PM',
    flightType: 'nonstop',
    duration: '5h 20m',
    date: 'Thu, 19 Aug',
    price: 350,
  },
];
