export const destinations = [
  {
    from: 'LAX',
    to: 'NYC',
    name: 'LA - New York',
    destinations: 13,
    image: '/HomeDestination/batu.jpg',
  },
  {
    from: 'MIA',
    to: 'DXB',
    name: 'Miami - Dubai',
    destinations: 42,
    image: '/HomeDestination/kuta.jpg',
  },
  {
    from: 'JFK',
    to: 'LON',
    name: 'New York - London',
    destinations: 13,
    image: '/HomeDestination/surabaya.jpg',
  },
  {
    from: 'LON',
    to: 'NYC',
    name: 'London - New York',
    destinations: 56,
    image: '/HomeDestination/malang.jpg',
  },
  {
    from: 'LON',
    to: 'LAX',
    name: 'London - LA',
    destinations: 8,
    image: '/HomeDestination/doemg.jpg',
  },
  {
    from: 'DXB',
    to: 'NYC',
    name: 'Dubai - New York',
    destinations: 17,
    image: '/HomeDestination/nusa_dua.jpg',
  },
  {
    from: 'LON',
    to: 'DXB',
    name: 'London - Dubai',
    destinations: 23,
    image: '/HomeDestination/bandung.jpg',
  },
  {
    from: 'JFK',
    to: 'LAX',
    name: 'New York - LA',
    destinations: 38,
    image: '/HomeDestination/sumatera.jpg',
  },
];

export const featuredDestinations = [
  {
    fromID: 'JFK',
    fromLocation: 'New York US',
    toID: 'BCN',
    toLocation: 'Barcelona Spain',
    name: 'Barcelona Tour',
    rating: 4.5,
    activities: 56,
    image: '/HomeDestination/batu.jpg',
  },
  {
    fromID: 'LHR',
    fromLocation: 'London United Kingdom',
    toID: 'RIO',
    toLocation: 'Rio de Janeiro Brazil',
    name: 'Brazilian Tour',
    rating: 4.4,
    activities: 34,
    image: '/HomeDestination/kuta.jpg',
  },
  {
    fromID: 'JFK',
    fromLocation: 'New York US',
    toID: 'DUB',
    toLocation: 'Dublin Ireland',
    name: 'Irish Tour',
    rating: 4.1,
    activities: 13,
    image: '/HomeDestination/surabaya.jpg',
  },
  {
    fromID: 'JFK',
    fromLocation: 'New York US',
    toID: 'SEL',
    toLocation: 'Seoul South Korea',
    name: 'Korea Tour',
    rating: 4.4,
    activities: 14,
    image: '/HomeDestination/malang.jpg',
  },
  {
    fromID: 'JFK',
    fromLocation: 'New York US',
    toID: 'LHR',
    toLocation: 'London United Kingdom',
    name: 'London, United States',
    rating: 3.5,
    activities: 72,
    image: '/HomeDestination/doemg.jpg',
  },
  {
    fromID: 'JFK',
    fromLocation: 'New York US',
    toID: 'DXB',
    toLocation: 'Dubai',
    name: 'Middle Eastern Tour',
    rating: 5.0,
    activities: 86,
    image: '/HomeDestination/bandung.jpg',
  },
];

export const topTour = [
  {
    country: 'Japan',
    city: 'Tokyo',
    popularPlaces: 10,
    image: '/HomeDestination/nusa_dua.jpg',
  },
  {
    country: 'Spain',
    city: 'Barcelona',
    popularPlaces: 10,
    image: '/HomeDestination/surabaya.jpg',
  },
  {
    country: 'Indonesia',
    city: 'Bali',
    popularPlaces: 10,
    image: '/HomeDestination/batu.jpg',
  },
];

export const explore = [
  {
    name: 'Comfort Space',
    country: 'Japan',
    city: 'Tokyo',
    distance: 1.2,
    roomsAvail: 375,
    rating: 4.91,
    noOfRatings: 147,
    price: 210,
    image: '/HomeDestination/nusa_dua.jpg',
  },
  {
    name: 'Comfort Space',
    country: 'Spain',
    city: 'Barcelona',
    distance: 1.2,
    roomsAvail: 375,
    rating: 4.91,
    noOfRatings: 147,
    price: 210,
    image: '/HomeDestination/surabaya.jpg',
  },
  {
    name: 'Comfort Space',
    country: 'Indonesia',
    city: 'Bali',
    distance: 1.2,
    roomsAvail: 375,
    rating: 4.91,
    noOfRatings: 147,
    price: 210,
    image: '/HomeDestination/batu.jpg',
  },
  {
    name: 'Comfort Space',
    country: 'Turkey',
    city: 'Mamaris',
    distance: 1.2,
    roomsAvail: 375,
    rating: 4.91,
    noOfRatings: 147,
    price: 210,
    image: '/HomeDestination/malang.jpg',
  },
];

export const trendingCities = [
  {
    city: 'Manila',
    rating: 4.91,
    noOfRatings: 147,
    price: 250,
    image: '/HomeDestination/batu.jpg',
  },
  {
    city: 'San Francisco',
    rating: 4.91,
    noOfRatings: 147,
    price: 250,
    image: '/HomeDestination/kuta.jpg',
  },
  {
    city: 'Frankfurt main',
    rating: 4.91,
    noOfRatings: 147,
    price: 250,
    image: '/HomeDestination/surabaya.jpg',
  },
  {
    city: 'Washington',
    rating: 4.91,
    noOfRatings: 147,
    price: 250,
    image: '/HomeDestination/malang.jpg',
  },
  {
    city: 'Stockholm',
    rating: 4.91,
    noOfRatings: 147,
    price: 250,
    image: '/HomeDestination/doemg.jpg',
  },
  {
    city: 'Seattle',
    rating: 4.91,
    noOfRatings: 147,
    price: 250,
    image: '/HomeDestination/nusa_dua.jpg',
  },
];

export const passions = [
  {
    hobby: 'Beach Hobby',
    rating: 4.91,
    noOfRatings: 147,
    image: '/HomeDestination/batu.jpg',
  },
  {
    hobby: 'Sports Trip',
    rating: 4.91,
    noOfRatings: 147,
    image: '/HomeDestination/kuta.jpg',
  },
  {
    hobby: 'City Tours',
    rating: 4.91,
    noOfRatings: 147,
    image: '/HomeDestination/surabaya.jpg',
  },
  {
    hobby: 'Hiking Trips',
    rating: 4.91,
    noOfRatings: 147,
    image: '/HomeDestination/malang.jpg',
  },
];
