export const explore = [
  {
    name: 'Cancun Flight',
    type: 'City, House',
    country: 'Turkey',
    city: 'Mamaris',
    image: '/HomeDestination/batu.jpg',
    rooms: 375,
    price: 420,
    rating: 5,
  },
  {
    name: 'Cancun Flight',
    type: 'City, House',
    country: 'Turkey',
    city: 'Mamaris',
    image: '/HomeDestination/kuta.jpg',
    rooms: 375,
    price: 420,
    rating: 5,
  },
  {
    name: 'Cancun Flight',
    type: 'City, House',
    country: 'Turkey',
    city: 'Mamaris',
    image: '/HomeDestination/surabaya.jpg',
    rooms: 375,
    price: 420,
    rating: 5,
  },
  {
    name: 'Cancun Flight',
    type: 'City, House',
    country: 'Turkey',
    city: 'Mamaris',
    image: '/HomeDestination/malang.jpg',
    rooms: 375,
    price: 420,
    rating: 5,
  },
];
